apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: $APPLICATION
  name: $APPLICATION
spec:
  replicas: 1
  selector:
    matchLabels:
      run: $APPLICATION
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: $APPLICATION
    spec:
      containers:
      - image: gcr.io/$GOOGLE_CLOUD_PROJECT/$IMAGE_TAG
        name: $APPLICATION
        command:
        - java
        args:
        - -Dspring.profiles.active=prod
        - -Xms1024M
        - -Xmx1024M
        - -jar
        - /app/main.jar
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
status: {}